version: 2.1

# Define the jobs we want to run for this project
jobs:
  build:
    docker:
      - image: circleci/node:14
        auth:
          username: $userdocker
          password: $password  # context / project UI env-var reference
    steps:
      - checkout
      - run:
            name: npm build
            command: npm build
      - run:
            name: react-scripts build
            command: react-scripts build
  test:
    docker:
      - image: circleci/node:14
        auth:
          username: $userdocker
          password: $password  # context / project UI env-var reference
    steps:
      - checkout
      - run: echo "this is the test job"

# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - build
      - test